version: '3.8'

services:
  postgres:
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  zookeeper:
    restart: always
  
  kafka:
    restart: always
  
  ksqldb-server:
    restart: always
  
  elasticsearch:
    restart: always
  
  minio:
    restart: always
  
  backend:
    restart: always
    environment:
      DEBUG: "False"
    command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
  
  frontend:
    restart: always
    command: npm run start
    build:
      args:
        NODE_ENV: production

  nginx:
    image: nginx:alpine
    container_name: blackroses-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - blackroses-network
    restart: always
